*** Variables ***
${relatorio_rede_reembolso_valores_agregados_lbl_rede_ou_reembolso}        xpath=*//h2[normalize-space() = 'Rede ou Reembolso']
${relatorio_rede_reembolso_valores_agregados_btn_csv}                      xpath=*//button[@id="csv"]
${relatorio_rede_reembolso_valores_agregados_lbl_grafico}                  xpath=//*[@id="chartContainer02"]//*[contains(text(),"Distribuição por Tipo de Fonte")]
