*** Variables ***
${relatorio_rede_reembolso_evolucao_por_metricas_lbl_evolucao_rede_reembolso}        xpath=*//h2[normalize-space() = 'Evolução Rede e Reembolso']
${relatorio_rede_reembolso_evolucao_por_metricas_btn_csv}                            xpath=*//button[@id="csv"]
${relatorio_rede_reembolso_evolucao_por_metricas_lbl_select_tipo_evento}              xpath=//*[@id="slide-container"]//*[contains(text(),"Tipo de Evento")]
${relatorio_rede_reembolso_evolucao_por_metricas_lbl_grafico }                        xpath=//*[@id="slide-container"]//*[contains(text(),"REDE")]