*** Variables ***
${relatorio_comparativo_anual_lbl_comparativo_anual}                xpath=*//h2[normalize-space()='Comparativo Anual']
${relatorio_comparativo_anual_btn_csv}                              xpath=*//button[@id="csv"]
${relatorio_comparativo_anual_btn_buscar}                           xpath=*//button[@id="filtrar"]
# ${relatorio_evolucoes_de_sinistro_ambulatorial_internacao_lbl_Grafico_custo_tipo_evento}                  xpath=*//div[@id="chartContainer01"]//*[contains(text(),"Custo por tipo de evento")]
# ${relatorio_evolucoes_de_sinistro_ambulatorial_internacao_lbl_Grafico_custo_por_evento}                   xpath=*//div[@id="chartContainer02"]//*[contains(text(),"Custo por evento")]