*** Variables ***
${relatorio_quantidade_pessoas_por_procedimentos_lbl_pessoas_por_procedimento}        xpath=*//h2[normalize-space() = 'Pessoas por Procedimento']
${relatorio_quantidade_pessoas_por_procedimentos_btn_csv}                             xpath=*//button[@id="csv"]                            
${relatorio_quantidade_pessoas_por_procedimentos_btn_next}                            xpath=*//a[@id='datatable-100_next' and normalize-space(.)='Next']
${relatorio_quantidade_pessoas_por_procedimentos_btn_previous}                        xpath=*//a[@id='datatable-100_previous' and normalize-space(.)='Previous']
