*** Variables ***
${relatorio_periodo_x_periodo_lbl_kpis_comparativo_por_periodo_selecionado}                xpath=*//h2[normalize-space() = 'KPIs - Comparativo por Período Selecionado']
${relatorio_periodo_x_periodo_btn_csv}                                                     xpath=*//button[@id="csv"]
${relatorio_periodo_x_periodo_btn_filtrar}                                                 xpath=*//button[@id="btn"]
# ${relatorio_evolucoes_de_sinistro_ambulatorial_internacao_lbl_Grafico_custo_tipo_evento}                  xpath=*//div[@id="chartContainer01"]//*[contains(text(),"Custo por tipo de evento")]
# ${relatorio_evolucoes_de_sinistro_ambulatorial_internacao_lbl_Grafico_custo_por_evento}                   xpath=*//div[@id="chartContainer02"]//*[contains(text(),"Custo por evento")]