*** Variables ***
${relatorio_sinistro_total_lbl_sinistro_consolidado_vs_microdados}              xpath=*//h2[normalize-space() = 'Comparativo Sinistro Consolidado vs Microdados']
${relatorio_sinistro_total_btn_csv}                                             xpath=*//button[@id="csv"]
# ${relatorio_evolucoes_de_sinistro_ambulatorial_internacao_lbl_Grafico_custo_tipo_evento}                  xpath=*//div[@id="chartContainer01"]//*[contains(text(),"Custo por tipo de evento")]
# ${relatorio_evolucoes_de_sinistro_ambulatorial_internacao_lbl_Grafico_custo_por_evento}                   xpath=*//div[@id="chartContainer02"]//*[contains(text(),"Custo por evento")]