*** Variables ***
${relatorio_run_off_lbl_run_off_periodo_completo}                                xpath=*//h2[normalize-space() = 'Run off - Período Completo']
${relatorio_run_off_btn_csv}                                                     xpath=*//button[@id="csv"]
${relatorio_run_off_btn_filtrar}                                                 xpath=*//button[@type="submit"]
# ${relatorio_evolucoes_de_sinistro_ambulatorial_internacao_lbl_Grafico_custo_tipo_evento}                  xpath=*//div[@id="chartContainer01"]//*[contains(text(),"Custo por tipo de evento")]
# ${relatorio_evolucoes_de_sinistro_ambulatorial_internacao_lbl_Grafico_custo_por_evento}                   xpath=*//div[@id="chartContainer02"]//*[contains(text(),"Custo por evento")]