*** Variables ***

${sinistro_procedimentos_lbl_sinistralidade_por_procedimentos}            xpath=*//h2[contains(text(),"Sinistralidade por Procedimento")]
${sinistro_procedimentos_table_data}                                      xpath=*//th[contains(text(),"Data")]
${sinistro_procedimentos_lbl_resultados_por_paginas}                      xpath=*//label[contains(text(),"resultados por página")]
