*** Variables ***

${guias_procedimentos_lbl_guias_procedimentos}            xpath=*//h2[contains(text(),"Guias de procedimentos")]
${guias_procedimentos_table_data}                         xpath=*//th[contains(text(),"Data")]
${guias_procedimentos_table_total_de_guias}               xpath=*//th[contains(text(),"Total de guias")]
${guias_procedimentos_table_medias}                       xpath=*//td[contains(text(),"Médias")]
${guias_procedimentos_lbl_guias_x_procedimentos}          xpath=//*[@class="raphael-group-12-caption"]