*** Variables ***
${relatorio_evolucoes_de_sinistro_consultas_valor_total_lbl_consultas_valor_total_ps_eletiva}             xpath=*//h2[normalize-space() = 'Consultas - Valor Total P.S. e Eletiva']
${relatorio_evolucoes_de_sinistro_consultas_valor_total_btn_csv}                                          xpath=*//button[@id="csv"]
${relatorio_evolucoes_de_sinistro_consultas_valor_total_lbl_Grafico}                                      xpath=*//div[@id="chartContainer01"]//*[contains(text(),"Consultas Valor Total P.S. e Eletiva")]
${relatorio_evolucoes_de_sinistro_consultas_valor_total_lbl_Grafico_filtro}                               xpath=*//div[@id="chartContainer01"]//*[contains(text(),"Consultas P.S.")]
