*** Variables ***
${relatorio_evolucoes_de_sinistro_per_capita_lbl_composicao_de_evento}               xpath=*//h2[normalize-space() = 'Sinistro per Capita']
${relatorio_evolucoes_de_sinistro_per_capita_btn_csv}                                xpath=*//button[@id="csv"]
${relatorio_evolucoes_de_sinistro_per_capita_lbl_mes_a_mes}                          xpath=//div[@id="chartContainer01"]//*[contains(text(),"Mês a mês")]
