*** Variables ***
${relatorio_evolucoes_de_sinistro_exames_lbl_evolucao_de_exames}                   xpath=*//h2[normalize-space() = 'Evolução de Exames']
${relatorio_evolucoes_de_sinistro_exames_btn_csv}                                  xpath=*//button[@id="csv"]
${relatorio_evolucoes_de_sinistro_exames_lbl_Grafico}                              xpath=*//div[@id="chartContainer02"]//*[contains(text(),"Demonstrativo gráfico")]
