*** Variables ***
${relatorio_evolucoes_de_sinistro_consultas_valor_medio_consultas_valor_medio_ps_eletiva}             xpath=*//h2[normalize-space() = 'Consultas - Valor Médio P.S. e Eletiva']
${relatorio_evolucoes_de_sinistro_consultas_valor_medio_btn_csv}                                  xpath=*//button[@id="csv"]
${relatorio_evolucoes_de_sinistro_consultas_valor_medio_lbl_Grafico}                              xpath=*//div[@id="chartContainer01"]//*[contains(text(),"Consultas Valor Médio P.S. e Eletiva")]
${relatorio_evolucoes_de_sinistro_consultas_valor_medio_lbl_Grafico_filtro}                       xpath=*//div[@id="chartContainer01"]//*[contains(text(),"Consultas P.S.")]
