*** Variables ***
${relatorio_evolucoes_de_sinistro_frequencia_ambulatoriais_lbl_evolucao_de_indicadores_amnulatoriai}                  xpath=*//h2[normalize-space() = 'Evolução de Indicadores Ambulatoriais']
${relatorio_evolucoes_de_sinistro_frequencia_ambulatoriais_btn_csv}                                                   xpath=*//button[@id="csv"]
${relatorio_evolucoes_de_sinistro_frequencia_ambulatoriais_lbl_Grafico_custo_tipo_evento}                             xpath=*//div[@id="chartContainer03"]//*[contains(text(),"Consulta Geral/Usuário ano")]
${relatorio_evolucoes_de_sinistro_frequencia_ambulatoriais_lbl_Grafico_exames_usuario_ano}                            xpath=*//div[@id="chartContainer02"]//*[contains(text(),"Exames/Usuário ano")]