*** Variables ***
${relatorio_evolucoes_de_sinistro_consultas_qtd_lbl_consultas_qtd_ps_eletiva}             xpath=*//h2[normalize-space() = 'Consultas - Qtde. P.S. e Eletiva']
${relatorio_evolucoes_de_sinistro_consultas_qtd_btn_csv}                                  xpath=*//button[@id="csv"]
${relatorio_evolucoes_de_sinistro_consultas_qtd_lbl_Grafico}                              xpath=*//div[@id="chartContainer01"]//*[contains(text(),"Consultas Qtde. P.S. e Eletiva")]
${relatorio_evolucoes_de_sinistro_consultas_qtd_lbl_Grafico_filtro}                       xpath=*//div[@id="chartContainer01"]//*[contains(text(),"Consultas P.S.")]
