*** Variables ***
${relatorio_evolucoes_de_sinistro_consultas_lbl_evolucao_de_consultas}                xpath=*//h2[normalize-space() = 'Evolução de Consultas']
${relatorio_evolucoes_de_sinistro_consultas_btn_csv}                                  xpath=*//button[@id="csv"]
${relatorio_evolucoes_de_sinistro_consultas_lbl_Grafico}                              xpath=*//div[@id="chartContainer02"]//*[contains(text(),"Demonstrativo gráfico")]
