*** Variables ***
${relatorio_evolucoes_de_sinistro_outros_lbl_evolucao_de_outros_custos}            xpath=//*[@id="slide-container"]/h2[contains(text(), "Evolução de 'outros' custos")]
${relatorio_evolucoes_de_sinistro_outros_btn_csv}                                  xpath=*//button[@id="csv"]
${relatorio_evolucoes_de_sinistro_outros_lbl_Grafico}                              xpath=*//div[@id="chartContainer02"]//*[contains(text(),"Demonstrativo gráfico")]
