*** Variables ***
${relatorio_evolucoes_de_sinistro_evo_tipo_de_evento_lbl_sinistro_por_tipo_evento}             xpath=*//h2[normalize-space() = 'Sinistro por Tipo de Evento']
${relatorio_evolucoes_de_sinistro_evo_tipo_de_evento_btn_csv}                                  xpath=*//button[@id="csv"]
${relatorio_evolucoes_de_sinistro_evo_tipo_de_evento_btn_buscar}                               xpath=*//button[@id="botao_buscar"]               
${relatorio_evolucoes_de_sinistro_evo_tipo_de_evento_lbl_Grafico}                              xpath=//div[@id="chartContainer01"]//*[contains(text(),"Distribuição por Tipo de Evento")]
