*** Variables ***
${relatorio_evolucoes_de_sinistro_internacoes_lbl_evolucao_de_internacoes}              xpath=*//h2[normalize-space() = 'Evolução de Internações']
${relatorio_evolucoes_de_sinistro_internacoes_btn_csv}                                  xpath=*//button[@id="csv"]
${relatorio_evolucoes_de_sinistro_internacoes_lbl_Grafico}                              xpath=*//div[@id="chartContainer02"]//*[contains(text(),"Sinistro Total (R$)")]
${relatorio_evolucoes_de_sinistro_internacoes_lbl_qtd_ps_internadas}                    xpath=//*[@id="n-internado"]
