*** Variables ***
${relatorio_evolucoes_de_sinistro_tratamento_lbl_evolucao_de_tratamento}              xpath=*//h2[normalize-space() = 'Evolução de Tratamento']
${relatorio_evolucoes_de_sinistro_tratamento_btn_csv}                                  xpath=*//button[@id="csv"]
${relatorio_evolucoes_de_sinistro_tratamento_lbl_Grafico}                              xpath=*//div[@id="chartContainer02"]//*[contains(text(),"Demonstrativo gráfico")]
