*** Variables ***
${relatorio_evolucoes_de_sinistro_evolucao_por_descritores_lbl_sinistro_evento}                  xpath=*//h2[normalize-space() = 'Sinistro por Evento']
${relatorio_evolucoes_de_sinistro_evolucao_por_descritores_btn_csv}                             xpath=*//button[@id="csv"]
${relatorio_evolucoes_de_sinistro_evolucao_por_descritores_btn_enviar}                          xpath=*//button[@id="enviar_form"]
