*** Variables ***
${relatorio_evolucoes_de_sinistro_evolucao_por_plano_lbl_sinistro_plano}                  xpath=*//h2[normalize-space() = 'Sinistro por Plano']
${relatorio_evolucoes_de_sinistro_evolucao_por_plano_btn_csv}                             xpath=*//button[@id="csv"]
${relatorio_evolucoes_de_sinistro_evolucao_por_plano_btn_enviar}                          xpath=*//button[@id="enviar_form"]
