*** Variables ***

${especialidades_lbl_sinistro_por_especialidade_do_evento}       xpath=*//h2[normalize-space() = 'Sinistro por Especialidade do Evento']
${especialidade_btn_csv}                                         xpath=*//button[@id="csv"]
${especialidade_btn_ultimo_mes}                                  xpath=*//a[contains(text(), 'Último mês')]
${especialidades_lbl_distribuicao_por_especialidade}             xpath=//*[local-name()='text' and text()='Distribuição por Especialidade']

