*** Variables ***

${individual_scripts_de_selecao_lbl_scripts_de_selecao}           xpath=*//h2[contains(text(),"Scripts de seleção")]
${individual_scripts_de_selecao_lbl_filtros_de_seguradora}        xpath=*//h4[contains(text(),"Filtros de Seguradora")]
${individual_scripts_de_selecao_lbl_filtros_de_rh}                xpath=*//h4[contains(text(),"Filtros de RH")]
${individual_scripts_de_selecao_lbl_buscar_salvar}                xpath=*//h4[contains(text(),"Buscar & Salvar")]

${individual_scripts_de_selecao_btn_filtrar}                      xpath=*//button[@class="btn btn-primary btn-block btn-sm btn-buscar"]