*** Variables ***

${individual_uso_constante_lbl_utilizacao_constante}                  xpath=*//h2[contains(text(),"Utilização Constante")]
${individual_uso_constante_btn_buscar}                                xpath=*//button[@class="empresa-buscar btn btn-default"][contains(text()," Buscar")]
${individual_uso_constante_btn_CSV}                                   xpath=*//div[@class='dt-buttons']//button[@class="dt-button"]//span[contains(text(),"CSV")]