*** Variables ***

${individual_recem_internados_lbl_recem_internados}                      xpath=*//h2[contains(text(),"Recém Internados")]
${individual_recem_internados_btn_filtrar}                               xpath=*//button[@class="empresa-buscar btn btn-primary"]
${individual_recem_internados_btn_CSV}                                   xpath=*//div[@class='dt-buttons']//button[@class="dt-button"]//span[contains(text(),"CSV")]