*** Variables ***

${individual_sem_eventos_lbl_sem_eventos}                           xpath=*//h2[contains(text(),"Sem eventos")]
${individual_sem_eventos_btn_buscar}                                xpath=*//button[@class="empresa-buscar btn btn-default btn-block"][contains(text()," Buscar")]
${individual_sem_eventos_btn_CSV}                                   xpath=*//div[@class='dt-buttons']//button[@class="dt-button"]//span[contains(text(),"CSV")]