*** Variables ***

${individual_hiperconsultadores_lbl_hiperconsultadores_eletivas}           xpath=*//h2[contains(text(),"Hiperconsultadores - Eletivas/P.S.")]
${individual_hiperconsultadores_utilizacao_btn_filtrar}                    xpath=*//button[@class="empresa-buscar btn-primary btn btn-default btn-block"]
${individual_hiperconsultadores_utilizacao_btn_CSV}                        xpath=*//div[@class='dt-buttons']//button[@class="dt-button"]//span[contains(text(),"CSV")]