*** Variables ***

${individual_crecentes_lbl_crecentes}                             xpath=*//h2[contains(text(),"Crescentes")]
${individual_crecentes_btn_filtrar}                               xpath=*//button[@class="empresa-buscar btn btn-primary btn-block"]
${individual_crecentes_btn_CSV}                                   xpath=*//div[@class='dt-buttons']//button[@class="dt-button"]//span[contains(text(),"CSV")]