*** Variables ***

${individual_hiperconsultadores_por_familia_lbl_hiperconsultadores_grupo_familiar}           xpath=*//h2[contains(text(),"Hiperconsultadores - Grupo Familiar")]
${individual_hiperconsultadores_por_familia_btn_filtrar}                                     xpath=*//button[@class="empresa-buscar btn btn-primary btn-block"]
${individual_hiperconsultadores_por_familia_btn_CSV}                                         xpath=*//div[@class='dt-buttons']//button[@class="dt-button"]//span[contains(text(),"CSV")]