*** Variables ***
${relatorio_sinistro_titularidade_e_sexo_lbl_sinistro_por_grupo}               xpath=*//h2[normalize-space() = 'Sinistro por Grupo']
${relatorio_sinistro_titularidade_e_sexo_btn_csv}                              xpath=*//button[@id="csv"]
${relatorio_sinistro_titularidade_e_sexo_lbl_sinistro_por_sexo}                xpath=//*[@id="slide-container"]//*[contains(text(),"Sinistro por Sexo")]
${relatorio_sinistro_titularidade_e_sexo_lbl_sinistro_por_titularidade}        xpath=//*[@id="slide-container"]//*[contains(text(),"Sinistro por Titularidade")]