*** Variables ***
${relatorio_sinistro_subestipulante_lbl_sinistro_por_subestipulante}               xpath=*//h2[normalize-space() = 'Sinistro por Subestipulante']
${relatorio_sinistro_subestipulante_btn_csv}                                       xpath=*//button[@id="csv"]
${relatorio_sinistro_subestipulante_btn_filtra}                                    xpath=*//button[@id="filtrar"]
${relatorio_sinistro_subestipulante_lbl_subestipulantes}                           xpath=*//label[@class='control-label col-sm-2']
