*** Variables ***

${dados_completos_lbl_dados_completos_nova_requisicao}                xpath=*//div[@id="content"]//h4[contains(text(),"Dados Completos (nova requisição)")]
${dados_completos_lbl_odonto}                                         xpath=*//a[@id="link_opcao_odonto"][contains(text(),"Odonto")]
${dados_completos_lbl_dados_completos_download}                       xpath=*//div[@id="content"]//h4[contains(text(),"Dados Completos (download)")]